apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: production
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-2
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: go-auth-secrets
  namespace: production
spec:
  refreshInterval: 5m # Check for secret updates every 5 minutes
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: go-auth-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: go-auth-api/production/db-password
    - secretKey: JWT_SECRET
      remoteRef:
        key: go-auth-api/production/jwt-secret
---
# External Secret for GitHub Container Registry access
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-image-pull-secret
  namespace: production
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: ghcr-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "ghcr.io": {
                "username": "PakornBank",
                "password": "{{ .githubToken }}",
                "auth": "{{ printf "PakornBank:%s" .githubToken | b64enc }}"
              }
            }
          }
  data:
    - secretKey: githubToken
      remoteRef:
        key: github/container-registry/access-token
