apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets-manager-argocd
  namespace: argocd
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-2
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-gitops-repo-secret
  namespace: argocd
spec:
  refreshInterval: 24h # Refresh daily
  secretStoreRef:
    name: aws-secrets-manager-argocd
    kind: SecretStore
  target:
    name: go-auth-gitops-repo
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: git@github.com:PakornBank/go-auth-k8s-manifests.git
        sshPrivateKey: "{{ .sshPrivateKey }}"
  data:
    - secretKey: sshPrivateKey
      remoteRef:
        key: argocd/gitops/ssh-private-key
